# Generated by Django 5.0.6 on 2024-06-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_wishlist_delete_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
