# Generated by Django 5.0.6 on 2024-06-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_userprofile_alternative_addresses_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alternative_addresses',
        ),
    ]
