# Generated by Django 5.0.6 on 2024-06-29 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_remove_userprofile_alternative_addresses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_street_address1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_street_address2',
            new_name='street_address2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_town_or_city',
            new_name='town_or_city',
        ),
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'default')},
        ),
    ]
