# Generated by Django 5.0.6 on 2024-06-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_rename_default_address_set_as_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
