# Generated by Django 5.0.6 on 2024-06-23 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_whishlist',
            field=models.ManyToManyField(blank=True, related_name='whishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
