# Generated by Django 5.0.6 on 2024-07-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='products.product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='five',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='four',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='one',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='three',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='two',
        ),
    ]
