# Generated by Django 5.0.6 on 2024-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rating_created_at_rating_review_alter_rating_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
