# Generated by Django 5.0.6 on 2024-07-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rating_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review',
            new_name='review_text',
        ),
    ]
