# Generated by Django 5.0.6 on 2024-07-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_review_rating_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review_text',
            new_name='review',
        ),
    ]
